services:
  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: catalog-service
    ports:
      - "8081:8081"

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: order-service
    ports:
      - "8082:8082"
    environment:
      CATALOG_SERVICE_URL: http://catalog-service:8081
    depends_on:
      - catalog-service

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: gateway
    ports:
      - "8000:8000"
    environment:
      CATALOG_SERVICE_URL: http://catalog-service:8081
      ORDER_SERVICE_URL: http://order-service:8082
    depends_on:
      - catalog-service
      - order-service
