@catalogHost = http://localhost:8081
@gatewayHost = http://localhost:8000

### 책 목록 조회
GET {{catalogHost}}/api/catalog/books

### 책 단건 조회
GET {{catalogHost}}/api/catalog/books/1

### 존재하지 않는 책 조회
GET {{catalogHost}}/api/catalog/books/999

### 책 등록
POST {{catalogHost}}/api/catalog/books
Content-Type: application/json

{
    "title": "Clean Architecture",
    "author": "Robert C. Martin",
    "price": 40000
}

### 책 수정
PUT {{catalogHost}}/api/catalog/books/1
Content-Type: application/json

{
    "title": "Spring Boot Start 2nd",
    "author": "Alice",
    "price": 30000
}

### 책 삭제
DELETE {{catalogHost}}/api/catalog/books/2

### Gateway - 책 목록 조회
GET {{gatewayHost}}/api/catalog/books